# spring configs
server:
  port: 8091

# resilience4j circuitbreaker configs
resilience4j.circuitbreaker:
  instances:
    testCircuitBreaker: # circuit breaker name
      registerHealthIndicator: true # enable health indicator for circuit breaker in actuator
      slidingWindowSize: 10 # consider the last 10 calls to calculate the failure rate
      permittedNumberOfCallsInHalfOpenState: 3 # in half open state, only 3 number of api calls are allowed
      slidingWindowType: COUNT_BASED # works on number of api calls hit, not the time
      minimumNumberOfCalls: 5 # at least 5 api call needs to happen before calculating the failure rate
      waitDurationInOpenState: 5s # how much time duration will circuit be open - means we can not check for the liveness of called service for this duration
      failureRateThreshold: 50 # 50% - when failure rate is more than or equal to 50%, circuit will be open
      eventConsumerBufferSize: 10 # buffered calls - this used to calculate failure rate - how much success calls get stored
      automaticTransitionFromOpenToHalfOpenEnabled: true # automatic transition between Open to Half Open


# resilience4j retry configs
resilience4j.retry:
  instances:
    testRetry:
      maxAttempts: 4 # max number of retries
      waitDuration: 10s # wait after 1st failure
      enableExponentialBackoff: true # exponentially increase wait duration between two retries
      exponentialBackoffMultiplier: 2 # multiplier using which the wait duration exponentially counted
      retryExceptions: # retry only if below exceptions thrown
        # - org.springframework.web.client.HttpServerErrorException
        # - java.io.IOException
      ignoreExceptions: # don't retry or ignore below exception
        # - io.github.robwin.exception.BusinessException



# resilience4j rate-limiter configs
resilience4j.ratelimiter:
  instances:
    testRateLimiter:
      limitForPeriod: 2 # max number of api calls allowed within the given period
      limitRefreshPeriod: 5s # period after which the rate limit is refreshed, after 5s again it will accept 2 calls
      timeoutDuration: 0 # requests which can't proceed immediately (due to the rate limiter) won’t wait and fail instantly.




# resilience4j time-limiter configs
resilience4j.timelimiter:
  instances:
    testTimeLimiter:
      timeoutDuration: 10s # time duration to run the task. If task is taking more than 10s, it will be interrupted
      cancelRunningFuture: true # cancel the future if timeout exceed and stop the execution


# actuator configs
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
